name: cs294
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - scipy
    - matplotlib
    - jupyter
    - pandas
    - seaborn
    - pip:
        - gym
        - tensorflow
          #- keras==1.2.1
